### ISSUE TITLE
force-app/main/default/objects/Contact/fields/CleanStatus.field-meta.xml  Could not resolve standard field's name. (135:13)

### ISSUE THREAD

**Issue by ashish-garg07** [trailheadapps/build-apps-with-lwc#5]
Hi Trailblazer,

If you are reading this, you may have found a bug on this Trailhead project.
If so, don't use this form to create a GitHub issue.
Instead, please use the Trailhead feedback to report it:
https://trailhead.salesforce.com/help?support=home

Many thanks 🐻

**Comment by muenzpraeger** [comment]
@pozil for you
